//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeadLock.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeadLock.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _lock {
            get {
                object obj = ResourceManager.GetObject("_lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap advancedsettings {
            get {
                object obj = ResourceManager.GetObject("advancedsettings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap allow {
            get {
                object obj = ResourceManager.GetObject("allow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap autosize {
            get {
                object obj = ResourceManager.GetObject("autosize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap details {
            get {
                object obj = ResourceManager.GetObject("details", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Language xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Author&gt;DeadLine&lt;/Author&gt;
        ///  &lt;Comment&gt;English&lt;/Comment&gt;
        ///  &lt;BarFile&gt;&amp;amp;File&lt;/BarFile&gt;
        ///  &lt;BarEdit&gt;&amp;amp;Edit&lt;/BarEdit&gt;
        ///  &lt;BarView&gt;&amp;amp;View&lt;/BarView&gt;
        ///  &lt;BarTools&gt;&amp;amp;Tools&lt;/BarTools&gt;
        ///  &lt;BarHelp&gt;&amp;amp;Help&lt;/BarHelp&gt;
        ///  &lt;BarItemOpenFiles&gt;Open file(s)...&lt;/BarItemOpenFiles&gt;
        ///  &lt;BarItemOpenFolder&gt;Open folder...&lt;/BarItemOpenFolder&gt;
        ///  &lt;BarItemRestart&gt;Restart&lt;/BarItemRestart&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eng {
            get {
                return ResourceManager.GetString("eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Language xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Author&gt;Pedro Cortés Díaz&lt;/Author&gt;
        ///  &lt;Comment&gt;Spanish&lt;/Comment&gt;
        ///  &lt;BarFile&gt;&amp;amp;Archivo&lt;/BarFile&gt;
        ///  &lt;BarEdit&gt;&amp;amp;Edición&lt;/BarEdit&gt;
        ///  &lt;BarView&gt;&amp;amp;Ver&lt;/BarView&gt;
        ///  &lt;BarTools&gt;&amp;amp;Herramientas&lt;/BarTools&gt;
        ///  &lt;BarHelp&gt;&amp;amp;Ayuda&lt;/BarHelp&gt;
        ///  &lt;BarItemOpenFiles&gt;Abrir archivo(s)...&lt;/BarItemOpenFiles&gt;
        ///  &lt;BarItemOpenFolder&gt;Abrir carpeta...&lt;/BarItemOpenFolder&gt;
        ///  &lt;BarItemResta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string esp {
            get {
                return ResourceManager.GetString("esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file {
            get {
                object obj = ResourceManager.GetObject("file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Language xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Author&gt;pouemes&lt;/Author&gt;
        ///  &lt;Comment&gt;Français&lt;/Comment&gt;
        ///  &lt;BarFile&gt;&amp;amp;Fichier&lt;/BarFile&gt;
        ///  &lt;BarEdit&gt;&amp;amp;Editer&lt;/BarEdit&gt;
        ///  &lt;BarView&gt;&amp;amp;Voir&lt;/BarView&gt;
        ///  &lt;BarTools&gt;&amp;amp;Outils&lt;/BarTools&gt;
        ///  &lt;BarHelp&gt;&amp;amp;Aide&lt;/BarHelp&gt;
        ///  &lt;BarItemOpenFiles&gt;Ouvrir fichier(s)...&lt;/BarItemOpenFiles&gt;
        ///  &lt;BarItemOpenFolder&gt;Ouvrir répertoire...&lt;/BarItemOpenFolder&gt;
        ///  &lt;BarItemRestart&gt;Redémarr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Language xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Author&gt;Ced999&lt;/Author&gt;
        ///  &lt;Comment&gt;German&lt;/Comment&gt;
        ///  &lt;BarFile&gt;&amp;amp;Datei&lt;/BarFile&gt;
        ///  &lt;BarEdit&gt;&amp;amp;Bearbeiten&lt;/BarEdit&gt;
        ///  &lt;BarView&gt;&amp;amp;Ansicht&lt;/BarView&gt;
        ///  &lt;BarTools&gt;&amp;amp;Werkzeuge&lt;/BarTools&gt;
        ///  &lt;BarHelp&gt;&amp;amp;Hilfe&lt;/BarHelp&gt;
        ///  &lt;BarItemOpenFiles&gt;Datei öffnen...&lt;/BarItemOpenFiles&gt;
        ///  &lt;BarItemOpenFolder&gt;Ordner öffnen...&lt;/BarItemOpenFolder&gt;
        ///  &lt;BarItemRestart&gt;Neustart&lt;/B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ger {
            get {
                return ResourceManager.GetString("ger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;Language&gt;
        ///	&lt;Author&gt;Sardor Tarik&lt;/Author&gt;
        ///	&lt;Comment&gt;Italian&lt;/Comment&gt;
        ///	&lt;BarFile&gt;&amp;amp;File&lt;/BarFile&gt;
        ///	&lt;BarEdit&gt;&amp;amp;Modifica&lt;/BarEdit&gt;
        ///	&lt;BarView&gt;&amp;amp;Visualizza&lt;/BarView&gt;
        ///	&lt;BarTools&gt;&amp;amp;Strumenti&lt;/BarTools&gt;
        ///	&lt;BarHelp&gt;&amp;amp;Aiuto&lt;/BarHelp&gt;
        ///	&lt;BarItemOpenFiles&gt;Apri file...&lt;/BarItemOpenFiles&gt;
        ///	&lt;BarItemOpenFolder&gt;Apri cartella...&lt;/BarItemOpenFolder&gt;
        ///	&lt;BarItemRestart&gt;Riavvia&lt;/BarItemRestart&gt;
        ///	&lt;BarItemExit&gt;Esci&lt;/BarItemExit&gt;
        ///	&lt;BarItemUnlock&gt;Sblocca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ita {
            get {
                return ResourceManager.GetString("ita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Language xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Author&gt;Jaehyung Lee&lt;/Author&gt;
        ///  &lt;Comment&gt;한국어&lt;/Comment&gt;
        ///  &lt;BarFile&gt;&amp;amp;파일&lt;/BarFile&gt;
        ///  &lt;BarEdit&gt;&amp;amp;편집&lt;/BarEdit&gt;
        ///  &lt;BarView&gt;&amp;amp;보기&lt;/BarView&gt;
        ///  &lt;BarTools&gt;&amp;amp;도구&lt;/BarTools&gt;
        ///  &lt;BarHelp&gt;&amp;amp;도움말&lt;/BarHelp&gt;
        ///  &lt;BarItemOpenFiles&gt;파일 열기...&lt;/BarItemOpenFiles&gt;
        ///  &lt;BarItemOpenFolder&gt;폴더 열기...&lt;/BarItemOpenFolder&gt;
        ///  &lt;BarItemRestart&gt;재시작&lt;/BarItemRestart&gt;
        ///  &lt;BarItemExit&gt;끝내기&lt;/BarIte [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string kor {
            get {
                return ResourceManager.GetString("kor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap license {
            get {
                object obj = ResourceManager.GetObject("license", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap move {
            get {
                object obj = ResourceManager.GetObject("move", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Language xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Author&gt;DeadLine&lt;/Author&gt;
        ///  &lt;Comment&gt;Dutch&lt;/Comment&gt;
        ///  &lt;BarFile&gt;&amp;amp;Bestand&lt;/BarFile&gt;
        ///  &lt;BarEdit&gt;&amp;amp;Aanpassen&lt;/BarEdit&gt;
        ///  &lt;BarView&gt;&amp;amp;Beeld&lt;/BarView&gt;
        ///  &lt;BarTools&gt;&amp;amp;Gereedschap&lt;/BarTools&gt;
        ///  &lt;BarHelp&gt;&amp;amp;Help&lt;/BarHelp&gt;
        ///  &lt;BarItemOpenFiles&gt;Open bestand(en)...&lt;/BarItemOpenFiles&gt;
        ///  &lt;BarItemOpenFolder&gt;Open folder...&lt;/BarItemOpenFolder&gt;
        ///  &lt;BarItemRestart&gt;Herstart [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nl {
            get {
                return ResourceManager.GetString("nl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ownership {
            get {
                object obj = ResourceManager.GetObject("ownership", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Language xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;Author&gt;Nickk888&lt;/Author&gt;
        ///	&lt;Comment&gt;Polish&lt;/Comment&gt;
        ///	&lt;BarFile&gt;&amp;amp;Plik&lt;/BarFile&gt;
        ///	&lt;BarEdit&gt;&amp;amp;Edytuj&lt;/BarEdit&gt;
        ///	&lt;BarView&gt;&amp;amp;Widok&lt;/BarView&gt;
        ///	&lt;BarTools&gt;&amp;amp;Narzędzia&lt;/BarTools&gt;
        ///	&lt;BarHelp&gt;&amp;amp;Pomoc&lt;/BarHelp&gt;
        ///	&lt;BarItemOpenFiles&gt;Otwórz plik(i)...&lt;/BarItemOpenFiles&gt;
        ///	&lt;BarItemOpenFolder&gt;Otwórz folder...&lt;/BarItemOpenFolder&gt;
        ///	&lt;BarItemRestart&gt;Zrestartuj&lt;/BarItemResta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pl {
            get {
                return ResourceManager.GetString("pl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap restart {
            get {
                object obj = ResourceManager.GetObject("restart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Language xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Author&gt;Leonid Gorokhov&lt;/Author&gt;
        ///  &lt;Comment&gt;Russian&lt;/Comment&gt;
        ///  &lt;BarFile&gt;&amp;amp;Файл&lt;/BarFile&gt;
        ///  &lt;BarEdit&gt;&amp;amp;Правка&lt;/BarEdit&gt;
        ///  &lt;BarView&gt;&amp;amp;Вид&lt;/BarView&gt;
        ///  &lt;BarTools&gt;&amp;amp;Инструменты&lt;/BarTools&gt;
        ///  &lt;BarHelp&gt;&amp;amp;Помощь&lt;/BarHelp&gt;
        ///  &lt;BarItemOpenFiles&gt;Открыть файл(ы)...&lt;/BarItemOpenFiles&gt;
        ///  &lt;BarItemOpenFolder&gt;Открыть папку...&lt;/BarItemOpenFolder&gt;
        ///  &lt;BarItemRestart&gt;Пере [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rus {
            get {
                return ResourceManager.GetString("rus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Language xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Author&gt;Nikola Janković&lt;/Author&gt;
        ///  &lt;Comment&gt;Srpski&lt;/Comment&gt;
        ///  &lt;BarFile&gt;&amp;amp;Datoteka&lt;/BarFile&gt;
        ///  &lt;BarEdit&gt;&amp;amp;Uredi&lt;/BarEdit&gt;
        ///  &lt;BarView&gt;&amp;amp;Pregled&lt;/BarView&gt;
        ///  &lt;BarTools&gt;&amp;amp;Alati&lt;/BarTools&gt;
        ///  &lt;BarHelp&gt;&amp;amp;Pomoć&lt;/BarHelp&gt;
        ///  &lt;BarItemOpenFiles&gt;Otvori fajl(ove)...&lt;/BarItemOpenFiles&gt;
        ///  &lt;BarItemOpenFolder&gt;Otvori folder...&lt;/BarItemOpenFolder&gt;
        ///  &lt;BarItemRestart&gt;Rest [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sr {
            get {
                return ResourceManager.GetString("sr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Language xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Author&gt;Mats Arvendal&lt;/Author&gt;
        ///  &lt;Comment&gt;Swedish&lt;/Comment&gt;
        ///  &lt;BarFile&gt;&amp;amp;Arkiv&lt;/BarFile&gt;
        ///  &lt;BarEdit&gt;&amp;amp;Redigera&lt;/BarEdit&gt;
        ///  &lt;BarView&gt;&amp;amp;Visa&lt;/BarView&gt;
        ///  &lt;BarTools&gt;&amp;amp;Verktyg&lt;/BarTools&gt;
        ///  &lt;BarHelp&gt;&amp;amp;Hjälp&lt;/BarHelp&gt;
        ///  &lt;BarItemOpenFiles&gt;Öppna fil(er)...&lt;/BarItemOpenFiles&gt;
        ///  &lt;BarItemOpenFolder&gt;Öppna mapp...&lt;/BarItemOpenFolder&gt;
        ///  &lt;BarItemRestart&gt;Starta om&lt;/B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string swe {
            get {
                return ResourceManager.GetString("swe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Language xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Author&gt;@bkrcrc_ (Twitter)&lt;/Author&gt;
        ///  &lt;Comment&gt;Turkish&lt;/Comment&gt;
        ///  &lt;BarFile&gt;&amp;amp;Dosya&lt;/BarFile&gt;
        ///  &lt;BarEdit&gt;&amp;amp;Düzenle&lt;/BarEdit&gt;
        ///  &lt;BarView&gt;&amp;amp;Göster&lt;/BarView&gt;
        ///  &lt;BarTools&gt;&amp;amp;Araçlar&lt;/BarTools&gt;
        ///  &lt;BarHelp&gt;&amp;amp;Yardım&lt;/BarHelp&gt;
        ///  &lt;BarItemOpenFiles&gt;Dosya(ları) aç...&lt;/BarItemOpenFiles&gt;
        ///  &lt;BarItemOpenFolder&gt;Klasör aç...&lt;/BarItemOpenFolder&gt;
        ///  &lt;BarItemRestart&gt;Yenid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tr {
            get {
                return ResourceManager.GetString("tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unlock {
            get {
                object obj = ResourceManager.GetObject("unlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap update {
            get {
                object obj = ResourceManager.GetObject("update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VirusTotal {
            get {
                object obj = ResourceManager.GetObject("VirusTotal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap visibility {
            get {
                object obj = ResourceManager.GetObject("visibility", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap website {
            get {
                object obj = ResourceManager.GetObject("website", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
